services:
  _defaults:
    public: true

  pumukit_baseplayer.trackurl: '@Pumukit\BasePlayerBundle\Services\TrackUrlService'
  pumukit_baseplayer.seriesplaylist: '@Pumukit\BasePlayerBundle\Services\SeriesPlaylistService'
  pumukit_baseplayer.twig_extension: '@Pumukit\BasePlayerBundle\Twig\BasePlayerExtension'
  pumukit_baseplayer.intro: '@Pumukit\BasePlayerBundle\Services\IntroService'
  pumukit_baseplayer.player_service: '@Pumukit\BasePlayerBundle\Services\PlayerService'
  pumukit_baseplayer.useragent_parser: '@Pumukit\BasePlayerBundle\Services\UserAgentParserService'
  pumukit_live.live: '@Pumukit\BaseLivePlayerBundle\Services\LiveService'
  pumukit_base_live_player.api: '@Pumukit\BaseLivePlayerBundle\Services\APIService'
  pumukitcore.ajax_session_close_listener: '@Pumukit\CoreBundle\EventListener\AjaxSessionCloseListener'
  pumukitcore.filter: '@Pumukit\CoreBundle\EventListener\FilterListener'
  pumukitcore.twig_extension: '@Pumukit\CoreBundle\Twig\CoreExtension'
  pumukitcore.listener.command_exception: '@Pumukit\CoreBundle\EventListener\ConsoleExceptionListener'
  pumukitcore.filter_service: '@Pumukit\CoreBundle\Services\FilterService'
  pumukitcore.import_mapping_data: '@Pumukit\CoreBundle\Services\ImportMappingDataService'
  pumukit_core.pagination_service: '@Pumukit\CoreBundle\Services\PaginationService'
  pumukitencoder.cpu: '@Pumukit\EncoderBundle\Services\CpuService'
  pumukitencoder.profile: '@Pumukit\EncoderBundle\Services\ProfileService'
  pumukitencoder.mmpropertyjob: '@Pumukit\EncoderBundle\Services\MultimediaObjectPropertyJobService'
  pumukitencoder.picextractor: '@Pumukit\EncoderBundle\Services\PicExtractorService'
  pumukitencoder.pic: '@Pumukit\EncoderBundle\Services\PicService'
  pumukitencoder.remove: '@Pumukit\EncoderBundle\EventListener\RemoveListener'
  pumukit_encoder.dynamic_pic_extractor: '@Pumukit\EncoderBundle\Services\DynamicPicExtractorService'
  pumukit.inspection: '@Pumukit\InspectionBundle\Services\InspectionFfprobeService'
  form.type.texti18n: '@Pumukit\NewAdminBundle\Form\Type\Base\TextI18nType'
  form.type.texti18nadvance: '@Pumukit\NewAdminBundle\Form\Type\Base\TextI18nAdvanceType'
  form.type.textareai18n: '@Pumukit\NewAdminBundle\Form\Type\Base\TextareaI18nType'
  form.type.customlanguage: '@Pumukit\NewAdminBundle\Form\Type\Base\CustomLanguageType'
  form.type.license: '@Pumukit\NewAdminBundle\Form\Type\Base\LicenseType'
  pumukitnewadmin.kernelexception.listener: '@Pumukit\NewAdminBundle\EventListener\ExceptionListener'
  pumukitnewadmin.twig_extension: '@Pumukit\NewAdminBundle\Twig\PumukitAdminExtension'
  pumukitnewadmin.series_search: '@Pumukit\NewAdminBundle\Services\SeriesSearchService'
  pumukitnewadmin.multimedia_object_search: '@Pumukit\NewAdminBundle\Services\MultimediaObjectSearchService'
  pumukitnewadmin.multimedia_object_sync: '@Pumukit\NewAdminBundle\Services\MultimediaObjectSyncService'
  pumukitnewadmin.user_stats: '@Pumukit\NewAdminBundle\Services\UserStatsService'
  pumukitnewadmin.tag_catalogue: '@Pumukit\NewAdminBundle\Services\TagCatalogueService'
  pumukitnewadmin.filter: '@Pumukit\NewAdminBundle\EventListener\FilterListener'
  pumukitnewadmin.menu: '@Pumukit\NewAdminBundle\Menu\ItemsList'
  pumukitnewadmin.mmobjlistbuttons: '@Pumukit\NewAdminBundle\Menu\ItemsList'
  pumukitnewadmin.mmobjmenu: '@Pumukit\NewAdminBundle\Menu\ItemsList'
  pumukitnewadmin.block: '@Pumukit\NewAdminBundle\Menu\BlocksList'
  pumukitnewadmin.seriesmenu: '@Pumukit\NewAdminBundle\Menu\ItemsList'
  pumukitnewadmin.twig_mmobjbuttons_extension: '@Pumukit\NewAdminBundle\Twig\MultimediaObjectButtonsExtension'
  pumukitnewadmin.catalogue_extension: '@Pumukit\NewAdminBundle\Twig\CatalogueExtension'
  pumukitnewadmin.translatecontroller: '@Pumukit\NewAdminBundle\Controller\TranslateController'
  pumukit_notification.sender: '@Pumukit\NotificationBundle\Services\SenderService'
  pumukit_notification.listener: '@Pumukit\NotificationBundle\Services\JobNotificationService'
  pumukitlive.legacyeventpic: '@Pumukit\SchemaBundle\Services\LegacyEventPicService'
  pumukitschema.schema.locale: '@Pumukit\SchemaBundle\EventListener\LocaleListener'
  pumukitschema.schema.remove: '@Pumukit\SchemaBundle\EventListener\RemoveListener'
  pumukitschema.schema.permissionprofile: '@Pumukit\SchemaBundle\EventListener\PermissionProfileListener'
  pumukit_schema.role: '@Pumukit\SchemaBundle\Services\RoleService'
  pumukitschema.schema.series: '@Pumukit\SchemaBundle\EventListener\SeriesListener'
  pumukitschema.schema.multimediaobject: '@Pumukit\SchemaBundle\EventListener\MultimediaObjectListener'
  pumukitschema.factory: '@Pumukit\SchemaBundle\Services\FactoryService'
  pumukitschema.seriespic: '@Pumukit\SchemaBundle\Services\SeriesPicService'
  pumukitschema.mmspic: '@Pumukit\SchemaBundle\Services\MultimediaObjectPicService'
  pumukitschema.mmsduration: '@Pumukit\SchemaBundle\Services\MultimediaObjectDurationService'
  pumukitschema.multimedia_object: '@Pumukit\SchemaBundle\Services\MultimediaObjectService'
  pumukitschema.multimedia_object_voter: '@Pumukit\SchemaBundle\Services\MultimediaObjectVoter'
  pumukitschema.sorted_multimedia_object: '@Pumukit\SchemaBundle\Services\SortedMultimediaObjectsService'
  pumukitschema.multimedia_object_views: '@Pumukit\SchemaBundle\EventListener\MultimediaObjectViews'
  pumukitschema.tag: '@Pumukit\SchemaBundle\Services\TagService'
  pumukitschema.series: '@Pumukit\SchemaBundle\Services\SeriesService'
  pumukitschema.announce: '@Pumukit\SchemaBundle\Services\AnnounceService'
  pumukitschema.permissionprofile_dispatcher: '@Pumukit\SchemaBundle\Services\PermissionProfileEventDispatcherService'
  pumukitschema.permissionprofile: '@Pumukit\SchemaBundle\Services\PermissionProfileService'
  pumukitschema.permission: '@Pumukit\SchemaBundle\Services\PermissionService'
  pumukitschema.multimediaobject_dispatcher: '@Pumukit\SchemaBundle\Services\MultimediaObjectEventDispatcherService'
  pumukitschema.user_dispatcher: '@Pumukit\SchemaBundle\Services\UserEventDispatcherService'
  pumukitschema.series_dispatcher: '@Pumukit\SchemaBundle\Services\SeriesEventDispatcherService'
  pumukitschema.group_dispatcher: '@Pumukit\SchemaBundle\Services\GroupEventDispatcherService'
  pumukitschema.link_dispatcher: '@Pumukit\SchemaBundle\Services\LinkEventDispatcherService'
  pumukitschema.material_dispatcher: '@Pumukit\SchemaBundle\Services\MaterialEventDispatcherService'
  pumukitschema.personwithrole_dispatcher: '@Pumukit\SchemaBundle\Services\PersonWithRoleEventDispatcherService'
  pumukitschema.pic_dispatcher: '@Pumukit\SchemaBundle\Services\PicEventDispatcherService'
  pumukitschema.track_dispatcher: '@Pumukit\SchemaBundle\Services\TrackEventDispatcherService'
  pumukitschema.link: '@Pumukit\SchemaBundle\Services\LinkService'
  pumukitschema.material: '@Pumukit\SchemaBundle\Services\MaterialService'
  pumukitschema.caption: '@Pumukit\SchemaBundle\Services\CaptionService'
  pumukitschema.track: '@Pumukit\SchemaBundle\Services\TrackService'
  pumukitschema.person: '@Pumukit\SchemaBundle\Services\PersonService'
  pumukitschema.user: '@Pumukit\SchemaBundle\Services\UserService'
  pumukitschema.group: '@Pumukit\SchemaBundle\Services\GroupService'
  pumukitschema.pic: '@Pumukit\SchemaBundle\Services\PicService'
  pumukitschema.stats: '@Pumukit\SchemaBundle\Services\StatsService'
  pumukitschema.text_index: '@Pumukit\SchemaBundle\Services\TextIndexService'
  pumukitschema.embeddedbroadcast: '@Pumukit\SchemaBundle\Services\EmbeddedBroadcastService'
  pumukitschema.special_translation: '@Pumukit\SchemaBundle\Services\SpecialTranslationService'
  pumukitschema.eventsession: '@Pumukit\SchemaBundle\Services\EmbeddedEventSessionService'
  pumukit_stats.log: '@Pumukit\StatsBundle\EventListener\Log'
  pumukit_stats.stats: '@Pumukit\StatsBundle\Services\StatsService'
  pumukit_web_tv.breadcrumbs: '@Pumukit\WebTVBundle\Services\BreadcrumbsService'
  pumukit_web_tv.channels: '@Pumukit\WebTVBundle\Services\ChannelService'
  pumukit_web_tv.categories_service: '@Pumukit\WebTVBundle\Services\CategoriesService'
  pumukit_web_tv.chapter_marks_service: '@Pumukit\WebTVBundle\Services\ChapterMarkService'
  pumukit_web_tv.link_service: '@Pumukit\WebTVBundle\Services\LinkService'
  pumukit_web_tv.list_service: '@Pumukit\WebTVBundle\Services\ListService'
  pumukit_web_tv.menu_service: '@Pumukit\WebTVBundle\Services\MenuService'
  pumukit_web_tv.search_service: '@Pumukit\WebTVBundle\Services\SearchService'
  pumukit_web_tv.twig_mongo_date_extension: '@Pumukit\WebTVBundle\Twig\MongoDateExtension'
  pumukit_web_tv.twig_bootstrap_extension: '@Pumukit\WebTVBundle\Twig\BootstrapExtension'
  pumukit_web_tv.twig_pumukit_extension: '@Pumukit\WebTVBundle\Twig\PumukitExtension'
  pumukit_workflow.job_generator_listener: '@Pumukit\WorkflowBundle\EventListener\JobGeneratorListener'
  pumukit_workflow.pic_extractor_listener: '@Pumukit\WorkflowBundle\EventListener\PicExtractorListener'
  pumukit_workflow.dynamic_pic_extractor_listener: '@Pumukit\WorkflowBundle\EventListener\DynamicPicExtractorListener'
  security.role_hierarchy: '@Pumukit\SchemaBundle\Security\RoleHierarchy'
