services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true
    bind:
      $pumukitWizardShowTags: '%pumukit_wizard.show_tags%'
      $pumukitWizardShowObjectLicense: '%pumukit_wizard.show_object_license%'
      $pumukitNewAdminLicenses: '%pumukit_new_admin.licenses%'
      $pumukitSchemaDefaultLicense: '%pumukitschema.default_license%'
      $pumukitWizardTagParentCod: '%pumukit_wizard.tag_parent_code%'
      $pumukitWizardMandatoryTitle: '%pumukit_wizard.mandatory_title%'
      $pumukitCustomLanguages: '%pumukit.customlanguages%'
      $locales: '%pumukit.locales%'
      $pumukitWizardReuseSeries: '%pumukit_wizard.reuse_series%'
      $pumukitWizardReuseAdminSeries: '%pumukit_wizard.reuse_admin_series%'
      $pumukitWizardSimpleDefaultMasterProfile: '%pumukit_wizard.simple_default_master_profile%'
      $pumukitWizardShowSimpleMmTitle: '%pumukit_wizard.show_simple_mm_title%'
      $pumukitWizardShowSimpleSeriesTitle: '%pumukit_wizard.show_simple_series_title%'

  Pumukit\WizardBundle\Controller\:
    resource: '../../src/Pumukit/WizardBundle/Controller/'
    tags: ['controller.service_arguments']

  Pumukit\WizardBundle\Command\:
    resource: '../../src/Pumukit/WizardBundle/Command/'
    tags: ['console.command']

  Pumukit\WizardBundle\Services\LicenseService:
    class: Pumukit\WizardBundle\Services\LicenseService
    arguments:
      $showLicense: '%pumukit_wizard.show_license%'
      $licenseDir:  '%pumukit_wizard.license_dir%'
      $locales:     '%pumukit.locales%'

  Pumukit\WizardBundle\Services\WizardService:
    class: Pumukit\WizardBundle\Services\WizardService
    arguments:
      $basePath:   '%kernel.project_dir%/'
      $locales:    '%pumukit.locales%'
      $inboxDepth: '%pumukit.inbox_depth%'

  Pumukit\WizardBundle\Services\FormEventDispatcherService:
    class: Pumukit\WizardBundle\Services\FormEventDispatcherService
