controllers:
    resource: ../../src/Pumukit/*/Controller/*
    type: annotation

pumukit_stats_ui:
  resource: "@PumukitStatsUIBundle/Resources/config/routing.yml"
  prefix:   /

# pumukit_jw_player:
#   resource: "@PumukitPlayerBundle/Resources/config/routing.yml"
#   prefix:   /

pumukit_base_player:
  resource: "@PumukitBasePlayerBundle/Resources/config/routing.yml"
  prefix:   /

pumukit_core:
  resource: "@PumukitCoreBundle/Resources/config/routing.yml"
  prefix:   /

pumukitwizard:
  resource: "@PumukitWizardBundle/Resources/config/routing.yml"

pumukit_web_tv_file:
  resource: "@PumukitWebTVBundle/Resources/config/routing.yml"
  prefix:   /

pumukitnewadmin:
  resource: "@PumukitNewAdminBundle/Resources/config/routing.yml"
  prefix:   /

pumukit_player:
  resource: "@PumukitPaellaPlayerBundle/Resources/config/routing.yml"
  prefix:   /
