pumukit_ldap_bundle:
    resource: "@PumukitLDAPBundle/Controller/"
    type:     annotation
    prefix:   /admin/ldap

pumukit_ldap_js:
    path: /ldap/ldap.js
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitLDAPBundle::ldap.js.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: js