pumukit_stats:
    resource: "@PumukitStatsBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_schema:
    resource: "@PumukitSchemaBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_opencast:
    resource: "@PumukitOpencastBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_encoder:
    resource: "@PumukitEncoderBundle/Controller/"
    type:     annotation
    prefix:   /

pumukitwizard:
    resource: "@PumukitWizardBundle/Resources/config/routing.yml"

pumukit_live:
    resource: "@PumukitLiveBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_new_admin_tmp:
    resource: "@PumukitNewAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

pumukit_web_tv_file:
    resource: @PumukitWebTVBundle/Resources/config/routing.yml
    prefix:   /

pumukit_encoder:
    resource: "@PumukitEncoderBundle/Controller/"
    type:     annotation
    prefix:   /

pumukitnewadmin:
    resource: @PumukitNewAdminBundle/Resources/config/routing.yml
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
