parameters:
  breadcrumbs_home_title:    'UPumukitTV'                 # 'Home' option title for the breadcrumbs service.
  catalogue_thumbnails:      true                         # If set to true, the full catalogue will list thumbnails instead of text.
  scroll_list_byuser:        false                        # If true, the list of multimedia objects and series of a user is not paginated.
  scroll_list_bytag:         false
  limit_objs_bytag:          12                           # ByTag Pager limit.   (Default 10)
  limit_objs_search:         12                           # Search Pager limit.  (Default 10)
  limit_objs_series:         12                           # Search Pager limit.  (Default 10)
  limit_objs_byuser:         12                           # ByUser Pager limit.   (Default 10)
  limit_objs_player_series:  12                           # Limit for mmobjs to appear on the mmobj player (Default 10)
  categories_tag_cod:        UNESCO
  categories.list_general_tags:  true
  search.parent_tag.cod:     UNESCO                      # Search controller option for the main tag search.
  search.parent_tag_2.cod:   null                         # Search controller option for the optional tag search.
  menu.announces_title:      'Latest Uploads'             # 'Announces' option title for the menu widget.
  menu.categories_title:     'By subject catalogue'       # 'Categories' option title for the menu widget.
  menu.home_title:           'Home'                       # 'Home' option title for the menu widget.
  menu.mediateca_title:      'Full Catalogue'             # 'Mediateca' option title for the menu widget.
  menu.show_stats:           false                        # To show stats on the menu or not. (Default true)
  menu.search_title:         'Multimedia objects search'  # 'Search' option title for the menu widget.
  show_mostviewed_lastmonth: false                        # If true it shows only the most viewed during last month.
  show_latest_with_pudenew:  true                        # Set whether to use the PUDENEW tag for 'Recently Added' and 'Latest Uploads'
  use_record_date_announces: false                        # Use record_date instead of public_data in announce list

  pumukit_web_tv.cinema_mode: true
  pumukit_web_tv.breadcrumbs_all_title: 'All'
  pumukit_web_tv.breadcrumbs_all_route: 'pumukit_webtv_medialibrary_index'

  pumukit_web_tv.breadcrumbs_parentweb:             # 'If set to an array, a 'parent' will always appear as first element in the breadcrumbs service.
#    title:  'Pumukit University'
#    url:    'http://www.pumukit.org'

  pumukit_web_tv.default_pic: '/bundles/pumukitwebtv/images/no_pic.jpg'
  pumukit_web_tv.linktagtosearch: false             # If set to true, the links to tags will link to a search template with the tag already selected on the search.

  pumukit_web_tv.media_library.filter_tags:
    - UNESCO

  pumukit.intro:             null                   # If set to an url, plays that url before every video.

  pumukit_web_tv.primary_color:   '#d66400'         # Primary color. Must be the same as in default_contrast_background in default.css.twig
  pumukit_web_tv.secondary_color: '#fff'            # Secondary color. Must be the same as in default_content_background in default.css.twig

  ############ MODULES CONFIGURATION #################
  hightlight.objects_by_col: 3
  recentlyadded.objects_by_col: 4
  mostviewed.objects_by_col: 4
  bytagblock.objects_by_col: 6
  limit_objs_mostviewed:     4                            # Mostviewed limit.     (Default 3)
  limit_objs_recentlyadded:  4                            # Recentlyadded limit.    (Default 3)
  limit_objs_hightlight: 3                                # HightLight limit.    (Default 3)
  columns_objs_announces:    4                            # Number of columns for announces. (Default 1)
  columns_objs_bytag:        4                            # Number of columns for bytag.  (Default 2)
  columns_objs_catalogue:    4                            # Number of columns for full catalogue. (Default 1)
  columns_objs_search:       4                            # Number of columns for search. (Default 2)
  columns_objs_byuser:       4                            # Number of columns for byuser.  (Default 2)
  columns_objs_event:       4                            # Number of columns for byuser.  (Default 2)

  live_block.objects_by_col: 3
  limit_objs_live_block: 3
  wall_block.wall_tag: 'PUDEWALL'

