pumukit_web_tv_parent:
    resource: "../../src/Pumukit/WebTVBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_web_tv:
    resource: "@PumukitWebTVBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_webtv_default_css:
    path: /webtv/css/webtv.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitWebTVBundle::custom.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css

homepage:
    path: /