pumukitnewadmin_mms_index:
    path: /series
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:index
        _sylius:
            filterable: true

pumukitnewadmin_mms_create:
    path: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:create
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_edit:
    path: /{id}/edit
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:edit

pumukitnewadmin_mms_links:
    path: /{id}/links
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:links

pumukitnewadmin_mms_update_meta:
    path: /{id}/update/meta
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updatemeta

pumukitnewadmin_mms_update_pub:
    path: /{id}/update/pub
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updatepub

pumukitnewadmin_mms_update_social:
    path: /{id}/update/social
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updatesocial

pumukitnewadmin_mms_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:batchDelete
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:delete

pumukitnewadmin_mms_generate_magic_url:
    path: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:generateMagicUrl

pumukitnewadmin_mms_clone:
    path: /{id}/clone
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:clone

pumukitnewadmin_mms_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:copy
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_show:
    path: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:show

pumukitnewadmin_mms_up:
    path: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:up
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_down:
    path: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:down
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_top:
    path: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:top
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_bottom:
    path: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:bottom
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_addtag:
    path: /{id}/addtag/
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:addTag
        _sylius:
            redirect: pumukitnewadmin_mms_edit

pumukitnewadmin_mms_deletetag:
    path: /{id}/deletetag/{tagId}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:deleteTag

pumukitnewadmin_mms_getchildrentag:
    path: /{id}/getchildrentag/
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:getChildrenTag

pumukitnewadmin_mms_searchtag:
    path: /search
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:searchTag

pumukitnewadmin_mms_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:list

pumukitnewadmin_mms_status:
    path: /{id}/status
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:status

pumukitnewadmin_mms_invert_announce:
    path: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:invertAnnounce

pumukitnewadmin_mms_cut:
    path: /cut
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:cut

pumukitnewadmin_mms_paste:
    path: /paste
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:paste

pumukitnewadmin_mms_reorder:
    path: /reorder
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:reorder

pumukitnewadmin_mms_reloadtags:
    path: /reloadtags
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:reloadTags

pumukitnewadmin_mms_sync_tags:
    path: /synctags
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:syncTags

pumukitnewadmin_mms_editgroups:
    path: /editgroups
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:editGroups

pumukitnewadmin_mms_updategroups:
    path: /updategroups
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updateGroups

pumukitnewadmin_mms_getgroups:
    path: /getgroups
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:getGroups

pumukitnewadmin_mms_broadcast_info:
    path: /{id}/broadcastinfo
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:getBroadcastInfo

pumukitnewadmin_mms_updatebroadcast:
    path: /{id}/updatebroadcast
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updateBroadcast

pumukitnewadmin_mms_sync_metadata:
    path: /{id}/sync/metadata
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:modalSyncMedatada

pumukitnewadmin_mms_update_sync_metadata:
    path: /{id}/update/sync/metadata
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updateMultimediaObjectSync

pumukitnewadmin_mms_user_last_relation:
    path: /user/lastrelation
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:userLastRelation

pumukitnewadmin_mms_listproperties:
    path: /{id}/listproperties
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:listProperties

pumukitnewadmin_mms_listexternalproperties:
    path: /{id}/listexternalplayer
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:listExternalPlayer

pumukitnewadmin_mms_delete_listexternalproperties:
    path: /{id}/deleteexternalvideo
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:deleteExternalProperty

pumukitnewadmin_mms_modal_preview:
    path: /{id}/modalpreview
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:modalPreview

pumukitnewadmin_mms_indexall:
    path: /mmslist
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:indexAll
        _sylius:
            filterable: true

pumukitnewadmin_mms_listall:
    path: /listAll
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:listAll

pumukitnewadmin_mms_updateProperty:
    path: /{id}/updateProperty
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObject:updateProperty
