pumukitnewadmin_mms_index:
    path: /series
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_mms_create:
    path: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::createAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_edit:
    path: /{id}/edit
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::editAction

pumukitnewadmin_mms_links:
    path: /{id}/links
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::linksAction

pumukitnewadmin_mms_update_meta:
    path: /{id}/update/meta
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updatemetaAction

pumukitnewadmin_mms_update_pub:
    path: /{id}/update/pub
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updatepubAction

pumukitnewadmin_mms_update_social:
    path: /{id}/update/social
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updatesocialAction

pumukitnewadmin_mms_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::deleteAction

pumukitnewadmin_mms_generate_magic_url:
    path: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::generateMagicUrlAction

pumukitnewadmin_mms_clone:
    path: /{id}/clone
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::cloneAction

pumukitnewadmin_mms_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::copyAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_show:
    path: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::showAction

pumukitnewadmin_mms_up:
    path: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::upAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_down:
    path: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::downAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_top:
    path: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::topAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_bottom:
    path: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::bottomAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_addtag:
    path: /{id}/addtag/
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::addTagAction
        _sylius:
            redirect: pumukitnewadmin_mms_edit

pumukitnewadmin_mms_deletetag:
    path: /{id}/deletetag/{tagId}
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::deleteTagAction

pumukitnewadmin_mms_getchildrentag:
    path: /{id}/getchildrentag/
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::getChildrenTagAction

pumukitnewadmin_mms_searchtag:
    path: /search
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::searchTagAction
        search_text:

pumukitnewadmin_mms_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::listAction

pumukitnewadmin_mms_status:
    path: /{id}/status
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::statusAction

pumukitnewadmin_mms_invert_announce:
    path: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::invertAnnounceAction

pumukitnewadmin_mms_cut:
    path: /cut
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::cutAction

pumukitnewadmin_mms_paste:
    path: /paste
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::pasteAction

pumukitnewadmin_mms_reorder:
    path: /reorder
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::reorderAction

pumukitnewadmin_mms_reloadtags:
    path: /reloadtags
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::reloadTagsAction

pumukitnewadmin_mms_sync_tags:
    path: /synctags
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::syncTagsAction

pumukitnewadmin_mms_editgroups:
    path: /editgroups
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::editGroupsAction

pumukitnewadmin_mms_updategroups:
    path: /updategroups
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updateGroupsAction

pumukitnewadmin_mms_getgroups:
    path: /getgroups
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::getGroupsAction

pumukitnewadmin_mms_broadcast_info:
    path: /{id}/broadcastinfo
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::getBroadcastInfoAction

pumukitnewadmin_mms_updatebroadcast:
    path: /{id}/updatebroadcast
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updateBroadcastAction

pumukitnewadmin_mms_sync_metadata:
    path: /{id}/sync/metadata
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::modalSyncMedatadaAction

pumukitnewadmin_mms_update_sync_metadata:
    path: /{id}/update/sync/metadata
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updateMultimediaObjectSyncAction

pumukitnewadmin_mms_user_last_relation:
    path: /user/lastrelation
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::userLastRelationAction

pumukitnewadmin_mms_listproperties:
    path: /{id}/listproperties
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::listPropertiesAction

pumukitnewadmin_mms_listexternalproperties:
    path: /listexternalplayer
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::listExternalPlayerAction

pumukitnewadmin_mms_delete_listexternalproperties:
    path: /{id}/deleteexternalvideo
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::deleteExternalPropertyAction

pumukitnewadmin_mms_modal_preview:
    path: /{id}/modalpreview
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::modalPreviewAction

# TODO: DIGIREPO REMOVE
#pumukitnewadmin_mms_indexall:
#    path: /mmslist
#    methods: [GET]
#    defaults:
#        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::indexAllAction
#        _sylius:
#            filterable: true
#
#pumukitnewadmin_mms_listall:
#    path: /listAll
#    methods: [GET, POST]
#    defaults:
#        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::listAllAction

pumukitnewadmin_mms_updateProperty:
    path: /{id}/updateProperty
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::updatePropertyAction
