pumukitnewadmin_series_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_series_search:
    pattern: /search
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:searchAction

pumukitnewadmin_series_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:createAction
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_links:
    pattern: /{id}/links
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:linksAction

pumukitnewadmin_series_update:
    pattern: /{id}/update
    methods: [GET, POST, DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.series:updateAction

pumukitnewadmin_series_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.series:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_series_list

pumukitnewadmin_series_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.series:deleteAction
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_generate_magic_url:
    pattern: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:generateMagicUrlAction

pumukitnewadmin_series_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:copyAction
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:showAction

pumukitnewadmin_series_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:listAction

pumukitnewadmin_series_invert_announce:
    pattern: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:invertAnnounceAction

pumukitnewadmin_series_changepub:
    pattern: /changepub
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:changePubAction

pumukitnewadmin_series_updatepub:
    pattern: /updatepub
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:updatePubAction

pumukitnewadmin_series_updatebroadcast:
    pattern: /{id}/updatebroadcast
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.series:updateBroadcastAction

pumukitnewadmin_series_listproperties:
    pattern: /{id}/listproperties
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.series:listPropertiesAction
