pumukitnewadmin_track_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:create

pumukitnewadmin_track_update:
    path: /{id}/update/{mmId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:update

pumukitnewadmin_track_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:upload

pumukitnewadmin_track_delete:
    path: /{id}/delete/{mmId}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Track:delete

pumukitnewadmin_track_up:
    path: /{id}/up/{mmId}
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:up

pumukitnewadmin_track_down:
    path: /{id}/down/{mmId}
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:down

pumukitnewadmin_track_list:
    path: /{id}/list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:list

pumukitnewadmin_track_info:
    path: /{id}/info/{mmId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:info

pumukitnewadmin_track_retry_job:
    path: /{mmId}/retry/{jobId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:retryJob

pumukitnewadmin_track_retry_track:
    path: /{mmId}/retry/{id}
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:retryTrack

pumukitnewadmin_track_delete_job:
    path: /{mmId}/deletejob
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Track:deleteJob

pumukitnewadmin_track_update_job:
    path: /{mmId}/updatejob
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:updateJobPriority

pumukitnewadmin_track_info_job:
    path: /job/{mmId}/info/{jobId}
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Track:infoJob

pumukitnewadmin_track_autocomplete:
    path: /{id}/autocomplete/{mmId}
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:autocomplete

pumukitnewadmin_track_pic:
    path: /{mmId}/{id}/pic
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:pic

pumukitnewadmin_track_download:
    path: /{mmId}/{id}/download
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:download

pumukitnewadmin_track_retranscode:
    path: /{mmId}/{id}/{profile}/retranscode
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:retranscode

pumukitnewadmin_track_play:
    path: /{id}/play/{mmId}
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Track:play

pumukitnewadmin_track_toggle_hide:
    pattern: /{id}/toggle_hide/{mmId}
    methods: [PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Track:toggleHide
