pumukitwizard_simple_index:
    pattern: /index/{id}
    methods: [GET]
    defaults:
        _controller: PumukitWizardBundle:Simple:index

pumukitwizard_simple_upload:
    pattern: /upload/{id}
    methods: [POST]
    defaults:
        _controller: PumukitWizardBundle:Simple:upload

pumukitwizard_simple_embedindex:
    pattern: /embedindex
    methods: [GET]
    defaults:
        _controller: PumukitWizardBundle:Simple:embedindex

pumukitwizard_simple_embedupload:
    pattern: /embedupload
    methods: [POST]
    defaults:
        _controller: PumukitWizardBundle:Simple:embedupload
