sylius_resource:
    resources:
        pumukitnewadmin.role:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Role
            classes:
                model: Pumukit\SchemaBundle\Document\Role
                controller: Pumukit\NewAdminBundle\Controller\SortableAdminController    
        pumukitnewadmin.user:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:User
            classes:
                model: Pumukit\SchemaBundle\Document\User
                controller: Pumukit\NewAdminBundle\Controller\AdminController
        pumukitnewadmin.person:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Person
            classes:
                model: Pumukit\SchemaBundle\Document\Person
                controller: Pumukit\NewAdminBundle\Controller\PersonController
        pumukitnewadmin.series:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Series
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\NewAdminBundle\Controller\SeriesController
        pumukitnewadmin.mmtemplate:
            driver: doctrine/mongodb-odm
            templates: PumukitnewadminBundle:MultimediaObjectTemplate
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectTemplateController
        pumukitnewadmin.mms:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:MultimediaObject
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController
        pumukitnewadmin.seriespic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\SeriesPicController
        pumukitnewadmin.mmspic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController
        pumukitnewadmin.link:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Link
            classes:
                model: Pumukit\SchemaBundle\Document\Link
                controller: Pumukit\NewAdminBundle\Controller\LinkController
        pumukitnewadmin.material:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Material
            classes:
                model: Pumukit\SchemaBundle\Document\Material
                controller: Pumukit\NewAdminBundle\Controller\MaterialController
        pumukitnewadmin.track:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Track
            classes:
                model: Pumukit\SchemaBundle\Document\Track
                controller: Pumukit\NewAdminBundle\Controller\TrackController
        pumukitnewadmin.live:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Live
            classes:
                model: Pumukit\LiveBundle\Document\Live
                controller: Pumukit\NewAdminBundle\Controller\AdminController
        pumukitnewadmin.event:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Event
            classes:
                model: Pumukit\LiveBundle\Document\Event
                controller: Pumukit\NewAdminBundle\Controller\EventController