pumukit_new_admin_parent:
    resource: "../../Controller/"
    type:     annotation
    prefix:   /admin

pumukit_new_admin:
    resource: "@PumukitNewAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

pumukitnewadmin_js:
    path: /admin/pumukit.js
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'PumukitNewAdminBundle::pumukit2.js.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: js

pumukitnewadmin_locale_js:
    path: /admin/pumukit.{_locale}.js
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'PumukitNewAdminBundle::pumukit2.js.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: js

pumukitnewadmin_css:
    path: /admin/pumukit.css
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'PumukitNewAdminBundle::pumukit2.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css


pumukit_jquery_ui_autocomplete_css:
    path: /admin/jquery_ui_autocomplete.css
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'PumukitNewAdminBundle::jquery-ui-autocomplete.css.twig'
        maxAge:       86400
        sharedAge:    86400
        _format: css

pumukitnewadmin_user:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/user.yml"
    prefix: /admin/user

pumukitnewadmin_person:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/person.yml"
    prefix: /admin/person

pumukitnewadmin_role:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/role.yml"
    prefix: /admin/role

pumukitnewadmin_series:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/series.yml"
    prefix: /admin/series

pumukitnewadmin_playlist:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/playlist.yml"
    prefix: /admin/playlist

pumukitnewadmin_collection:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/collection.yml"
    prefix: /admin/collection

pumukitnewadmin_mms:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/mms.yml"
    prefix: /admin/mms

pumukitnewadmin_mms_shortener:
    path: /admin/mm/{id}/
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController::shortenerAction

pumukitnewadmin_playlistmms:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/playlistmms.yml"
    prefix: /admin/playlist/mms

pumukitnewadmin_playlistpic:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/playlistpic.yml"
    prefix: /admin/playlistpic

pumukitnewadmin_seriespic:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/seriespic.yml"
    prefix: /admin/seriespic

pumukitnewadmin_mmspic:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/mmspic.yml"
    prefix: /admin/mmspic

pumukitnewadmin_seriestype:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/seriestype.yml"
    prefix: /admin/seriestype

pumukitnewadmin_tag:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/tag.yml"
    prefix: /admin/tag

pumukitnewadmin_link:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/link.yml"
    prefix: /admin/link

pumukitnewadmin_material:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/material.yml"
    prefix: /admin/material

pumukitnewadmin_track:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/track.yml"
    prefix: /admin/track

pumukitnewadmin_live:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/live.yml"
    prefix: /admin/live

pumukitnewadmin_event:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/legacyevent.yml"
    prefix: /admin/event

pumukitnewadmin_eventpic:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/legacyeventpic.yml"
    prefix: /admin/eventpic

pumukitnewadmin_permission_profile:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/permissionprofile.yml"
    prefix: /admin/permissionprofile

pumukitnewadmin_group:
    resource: "@PumukitNewAdminBundle/Resources/config/routes/group.yml"
    prefix: /admin/group

pumukitnewadmin_metadata_translate:
    path: /admin/metadata/translate
    defaults:
        _controller: pumukitnewadmin.translatecontroller:indexAction

